Improving Vagrant setup a bit more

diff --git a/ssh-test-setup-centos7/Vagrantfile b/ssh-test-setup-centos7/Vagrantfile
--- a/ssh-test-setup-centos7/Vagrantfile
+++ b/ssh-test-setup-centos7/Vagrantfile
@@ -4,49 +4,80 @@ require_relative 'common-functions'
 mongodb_version = "4.0"
 num_test_servers= 3
 
-Vagrant.configure("2") do |config|
-  # Generate the TLS certs if they don't exist yet
-  CommonSetupFunctions.setupTLSCerts(ARGV[0], num_test_servers)
+$conditional_install_mongodb = <<-INSTALL_SCRIPT
+if [ ! -f /etc/yum/repos.d/mongodb-org-#{mongodb_version}.repo ]; then
+      [ -d /etc/yum/repos.d ] || sudo mkdir -p /etc/yum/repos.d
+      sudo mv /home/vagrant/mongodb-org-#{mongodb_version}.repo /etc/yum/repos.d/
+fi
+if ! rpm --quiet --query mongodb-org; then
+   echo "MongoDB binaries not found, installing"
+   sudo yum install -y mongodb-org
+fi
+INSTALL_SCRIPT
 
-  # Regen the ssh keys used to communicate between testdriver and rs[1-3] if we're in up or provision mode
-  insecure_ssh_pub_key = CommonSetupFunctions.setupSSHKeys(ARGV[0])
+# Generate the TLS certs if they don't exist yet
+CommonSetupFunctions.setupTLSCerts(ARGV[0], num_test_servers)
+
+# Regen the ssh keys used to communicate between testdriver and rs[1-3] if we're in up or provision mode
+insecure_ssh_pub_key = CommonSetupFunctions.setupSSHKeys(ARGV[0])
   
+
+Vagrant.configure("2") do |config|
   if Vagrant.has_plugin?("vagrant-cachier")
+    puts("Configured vagrant-cachier")
     config.cache.scope = :box
   end
 
-  config.vm.box = "bento/centos-7.9"
-
-  config.vm.provider "docker" do |d, override|
-    d.image = "centos:7"
-  end
+  # config.vm.provider "docker" do |d, override|
+  #   puts("Docker-specific configuration")
+  #   d.image = "centos:7"
+  # end
   
   config.vm.provider "virtualbox" do |vb|
     #override.vm.box = "bento/centos-7.9"
     #vb.customize ["modifyvm", :id, "--cpus", "1", "--memory", "1024"]
+    puts("Configuring VirtualBox provider")
     vb.memory = 1024
     vb.cpus = 1
-#   vb.linked_clone  = true
+    #vb.linked_clone = true
+    vb.linked_clone = true
   end
+
+  #config.vm.box = "bento/centos-7.9"
 
   config.vbguest.installer_options[:allow_kernel_upgrade] = true
   config.vbguest.installer_hooks[:before_install] = ["yum install -y deltarpm"]
-  
+
+  config.vm.provision "hosts", :sync_hosts => true
+  config.vm.synced_folder ".", "/vagrant", disabled: true
+
+  if ARGV[0] == "up" || ARGV[0] == 'provision'
+    config.vm.provision "shell", inline: "[ -d /home/vagrant/tls ] || mkdir -p tls", privileged: false
+    config.vm.provision "shell", inline: "[ -d /home/vagrant/.ssh/ ] || mkdir /home/vagrant/.ssh", privileged: false
+    
+    config.vm.provision "file",  source: "tls/CA/root.crt", destination: "tls/root.crt"
+    config.vm.provision "shell", inline: '[ -d /etc/yum/repos.d ] || sudo mkdir -p /etc/yum/repos.d'
+    config.vm.provision "file",  source: "mongo-yum-#{mongodb_version}.repo", destination: "mongodb-org-#{mongodb_version}.repo"
+    config.vm.provision "shell", inline: $conditional_install_mongodb    
+  end
+
   # Create a three node RS, all with the same configuration
   (1..3).each do |i|
     config.vm.define "rs-#{i}" do |node|
+      node.vm.box = 'bento/centos-7.9'
       node_ip = 73 + i
-      node.vm.network "private_network", ip: "192.168.31.#{node_ip}"
+      node.vm.network "private_network", ip: "192.168.56.#{node_ip}"
       node.vm.hostname = "rs#{i}.mongodb.test"
-      node.vm.synced_folder ".", "/vagrant", disabled: true
-      node.vm.provision "hosts", :sync_hosts => true
-      ['mongod-ssh-rs.conf', 'mongod-ssh-ssl.conf', 'mongod-ssh-x509.conf', 'mongod-ssh-x509-noauth.conf'].each do |filename|
-        node.vm.provision 'file',source: filename, destination: filename
-      end        
+      #node.vm.synced_folder ".", "/vagrant", disabled: true
+      #node.vm.provision "hosts", :sync_hosts => true
+      
       if ARGV[0] == "up" || ARGV[0] == 'provision'
-        node.vm.provision "shell", inline: "[ -d /home/vagrant/tls ] || mkdir -p tls", privileged: false
+        ['mongod-ssh-rs.conf', 'mongod-ssh-ssl.conf', 'mongod-ssh-x509.conf', 'mongod-ssh-x509-noauth.conf'].each do |filename|
+          node.vm.provision 'file',source: filename, destination: filename
+        end       
+        #node.vm.provision "shell", inline: "[ -d /home/vagrant/tls ] || mkdir -p tls", privileged: false
         node.vm.provision "file",  source: "tls/rs#{i}/rs#{i}.pem", destination: "tls/mongo.pem"
-        node.vm.provision "file",  source: "tls/CA/root.crt", destination: "tls/root.crt"
+        #node.vm.provision "file",  source: "tls/CA/root.crt", destination: "tls/root.crt"
         ['data','data-ssl','data-x509'].each do |dir|
           node.vm.provision "shell", inline: "[ -d /home/vagrant/#{dir} ] || mkdir -p #{dir}", privileged: false
         end
@@ -59,15 +90,16 @@ Vagrant.configure("2") do |config|
           node.vm.provision "shell", inline: "chown vagrant:vagrant #{destname} ; chmod 600 #{destname}"
         end
       end
-      node.vm.provision "file",  source: "mongo-yum-#{mongodb_version}.repo", destination: "mongodb-org-#{mongodb_version}.repo"
-      node.vm.provision "shell", inline: '[ -d /etc/yum/repos.d ] || sudo mkdir -p /etc/yum/repos.d'
-      node.vm.provision "shell", inline: "sudo mv /home/vagrant/mongodb-org-#{mongodb_version}.repo /etc/yum/repos.d/"
-      node.vm.provision "shell", inline: 'sudo yum install -y mongodb-org'
+      #node.vm.provision "file",  source: "mongo-yum-#{mongodb_version}.repo", destination: "mongodb-org-#{mongodb_version}.repo"
+      #node.vm.provision "shell", inline: '[ -d /etc/yum/repos.d ] || sudo mkdir -p /etc/yum/repos.d'
+      #node.vm.provision "shell", inline: "sudo mv /home/vagrant/mongodb-org-#{mongodb_version}.repo /etc/yum/repos.d/"
+      #node.vm.provision "shell", inline: 'sudo yum install -y mongodb-org'
+      #node.vm.provision "shell", inline: $conditional_install_mongodb
       node.vm.provision "shell", inline: <<-SSHD_CONFIG
         sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
         systemctl restart sshd.service
       SSHD_CONFIG
-      node.vm.provision "shell", inline: "[ -d /home/vagrant/.ssh/ ] || mkdir /home/vagrant/.ssh", privileged: false
+      #node.vm.provision "shell", inline: "[ -d /home/vagrant/.ssh/ ] || mkdir /home/vagrant/.ssh", privileged: false
       node.vm.provision "shell", inline: "echo #{insecure_ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys", privileged: false
       node.vm.provision "file",  source: "mongod-service.conf", destination: "mongod-service.conf"
       node.vm.provision "shell", inline: "sudo mv mongod-service.conf /etc/mongod.conf"
@@ -77,26 +109,30 @@ Vagrant.configure("2") do |config|
       # node.vm.provider "virtualbox" do |vb|
       #   vb.customize ["modifyvm", :id, "--cpus", "1", "--memory", "1024"]
       # end
-      # node.vm.provision :reload
+      # vagnode.vm.provision :reload
       node.vm.provision "shell", inline: '$HOME/start-mongod-replset-node.sh', privileged: false
     end
   end
-
+  
   config.vm.define :testdriver do |tester|
-    tester.vm.network :private_network, ip: "192.168.31.98"
+    tester.vm.box = 'bento/centos-7.9'
+    tester.vm.network :private_network, ip: "192.168.56.98"
     tester.vm.hostname = "testdriver.mongodb.test"
     if ARGV[0] == "up" || ARGV[0] == 'provision'
-      tester.vm.provision "shell", inline: "[ -d /home/vagrant/tls ] || mkdir -p tls", privileged: false
+      #tester.vm.provision "shell", inline: "[ -d /home/vagrant/tls ] || mkdir -p tls", privileged: false
       tester.vm.provision "file",  source: "tls/testdriver/testdriver.pem", destination: "tls/testdriver.pem"
-      tester.vm.provision "file",  source: "tls/CA/root.crt",    destination: "tls/root.crt"
+      #tester.vm.provision "file",  source: "tls/CA/root.crt",    destination: "tls/root.crt"
       tester.vm.provision "file",  source: 'tls/user-cert/user-cert.pem', destination: 'tls/user-cert.pem'
-      tester.vm.provision "shell", inline: "[ -d /home/vagrant/.ssh ] || mkdir /home/vagrant/.ssh", privileged: false
+      #tester.vm.provision "shell", inline: "[ -d /home/vagrant/.ssh ] || mkdir /home/vagrant/.ssh", privileged: false
       tester.vm.provision "file",  source: 'ssh/id_ed25519', destination: '.ssh/id_ed25519'
       tester.vm.provision "file",  source: 'ssh/id_ed25519.pub', destination: '.ssh/id_ed25519.pub'
     end
     #tester.vm.provision "file",  source: "init-replicaset.js", destination: "init-replicaset.js"
-    tester.vm.provision "file",  source: "config-timeouts.js", destination: "config-timeouts.js"
-    tester.vm.provision "file",  source: "setup-test-env.sh",  destination: "setup-test-env.sh"
+    ['config-timeouts.js', 'setup-test-env.sh'].each do |file|
+      tester.vm.provision 'file', source: file, destination: file
+    end
+    #tester.vm.provision "file",  source: "config-timeouts.js", destination: "config-timeouts.js"
+    #tester.vm.provision "file",  source: "setup-test-env.sh",  destination: "setup-test-env.sh"
     tester.vm.provision "shell", inline: 'sudo yum install -y java-11-openjdk git emacs-nox wget tmux gcc python3 python3-pip python3-devel'
     tester.vm.provision "shell", inline: "sudo pip3 install mtools psutil pymongo"
     tester.vm.provision 'shell', inline: <<-LEIN_INSTALL
@@ -110,12 +146,12 @@ Vagrant.configure("2") do |config|
     fi
     LEIN_INSTALL
     tester.vm.provision "shell", inline: '[ -d /etc/yum/repos.d ] || sudo mkdir -p /etc/yum/repos.d'
-    tester.vm.provision 'file',  source: "mongo-yum-#{mongodb_version}.repo", destination: "mongodb-org-#{mongodb_version}.repo"
-    tester.vm.provision "shell", inline: "sudo mv /home/vagrant/mongodb-org-#{mongodb_version}.repo /etc/yum/repos.d/"
-    tester.vm.provision "shell", inline: 'sudo yum install -y mongodb-org'
+    #tester.vm.provision 'file',  source: "mongo-yum-#{mongodb_version}.repo", destination: "mongodb-org-#{mongodb_version}.repo"
+    #tester.vm.provision "shell", inline: "sudo mv /home/vagrant/mongodb-org-#{mongodb_version}.repo /etc/yum/repos.d/"
+    #tester.vm.provision "shell", inline: 'sudo yum install -y mongodb-org'
     tester.vm.provision "shell", inline: "mkdir -p git-repo/mdb-runtime-tester"
-    tester.vm.provision "hosts", :sync_hosts => true
-    tester.vm.synced_folder ".", "/vagrant", disabled: true
+    #tester.vm.provision "hosts", :sync_hosts => true
+    #tester.vm.synced_folder ".", "/vagrant", disabled: true
     tester.vm.synced_folder "../../mdb-runtime-tester/", "/home/vagrant/git-repo/mdb-runtime-tester"
     tester.vm.synced_folder '../../clj-pem-decoder/', '/home/vagrant/git-repo/clj-pem-decoder'
     tester.vm.provider "virtualbox" do |vb|
